contiv/auth_proxy

auth/auth.go
auth/ldap/ldap.go
auth/token.go
proxy/handlers.go
proxy/proxy.go
systemtests/local_user_test.go
systemtests/rbac_test.go

Re-opening PR https://github.com/contiv/auth_proxy/pull/89 again  as i'm not able update the old one due to visibility changes made to the repo. 
Signed-off-by: Yuva Shankar yuva29@users.noreply.github.com

Support to update local user details if the caller is either the same user or admin

---

systemtests/auth_test.go

Fixes https://github.com/contiv/ccn/issues/68

System test for authorization CRUD operations

---

proxy/handlers.go
proxy/helpers.go
proxy/proxy.go
systemtests/basic_test.go
systemtests/init_test.go
systemtests/ldap_management_test.go

One of the TODO item + fix (POST->PUT for LDAP endpoint).

System test for LDAP CRUD operations + Change LDAP POST to PUT

---

proxy/rbac.go
systemtests/rbac_test.go

Allow GET access on /inspect/globals/global/ to everyone

---

proxy/helpers.go
systemtests/local_user_test.go

Address special characters in local username

---

db/ldap_test.go

Thanks @rhim for finding this out.

Fix broken DB unit-tests

---

auth/auth.go
main.go

Remove initial-setup flag + add local users when proxy starts

---

scripts/build.sh

Use https instead of ssh when cloning so that it works with CI

---

Makefile

Cleaned up Makefile and removed references to non-existent targets

---

scripts/build.sh

Remove build/output/auth_proxy binary after building image

---

RELEASE.md
scripts/release.sh

Signed-off-by: Himanshu Raj <rhim@users.noreply.github.com>

WIP: a simplified release process for auth_proxy

---

scripts/build.sh

Fixes #96 
Tested on stock CentOS 7.3 with SELinux in enforcing mode

Removed check for SELinux because building now works with it enabled

---

common/utils.go
proxy/rbac.go
systemtests/basic_test.go

Added "Cache-Control: no-store" to all auth_proxy routes

---

docker-compose.yml
scripts/systemtests.sh
scripts/unittests.sh

Update from etcd 2.3.7 to 2.3.8 to match netplugin

---

systemtests/auth_test.go

This is done here: https://github.com/contiv/auth_proxy/blob/master/db/local.go#L155-L158

Remove addressed TODO

---

systemtests/auth_test.go
systemtests/ldap_management_test.go

This PR is just to maintain consistency. 

Change ccn.example.com to contiv.ad.local

---

auth/ldap/ldap.go

Minor nit for better debugging

---

Makefile

Fixes https://github.com/contiv/auth_proxy/issues/136

Added `build` as a dependency for all targets which need a local image, but only perform the build once per `make` run

---

Makefile

This reverts commit e80454b4ba51c94a0f9403dd43dd12beb1e8683c.

Revert "Added `build` as a dependency for all targets which need a local image, but only perform the build once per `make` run"

---

build/Dockerfile.build

build/Dockerfile.build: bump Go to 1.7.6

---

build/Dockerfile.base
build/Dockerfile.checks
build/Dockerfile.systemtests

Switched to Go 1.7.6 in all remaining spots

---

scripts/build.sh

scripts/build.sh: perform an explicit `git fetch` to pull in tags when building a custom $BUILD_VERSION

---

main.go
scripts/build.sh

merging for release 1.1.1

---

CONTRIBUTING.md
GOVERNANCE.md

Signed-off-by: Himanshu Raj <himansh@cisco.com>

Adding contribution and governance guidelines.

---

.dockerignore
.gitignore
Makefile
build/Dockerfile.checks
build/Dockerfile.release
scripts/build.sh
scripts/checks_in_container.sh
ui/backend/backendConfig.sh
ui/backend/serviceInit.sh

Also, fixed some `shfmt` shenanigans (see second commit's message)

updated build process to use local ui dir rather than a clone

---

.dockerignore
Dockerfile

Add Dockerfile for dockerhub automatic build
Signed-off-by: Wei Tie <nuaafe@gmail.com>

Add Dockerfile for dockerhub automatic build
