contiv/auth_proxy

auth/ldap/ldap.go, db/ldap.go, proxy/helpers.go, systemtests/basic_test.go
Windows VM kept shutting because of the expired license(which caused the tests to fail). 
Below are the changes made to the AD VM:
1. Extended the license for another 30 days as suggested here https://github.com/xdissent/ievms/issues/22 (Seems to be working fine)
2. Enabled LDAP over SSL so we can test SSL/TLS connections.
This PR also contains fixes for the bugs(LDAP config update) identified during testing.
=> Re-enable LDAP system tests + Test LDAP StartTLS() + Fixes

auth/policy.go, auth/token.go, systemtests/auth_test.go, systemtests/basic_test.go, systemtests/rbac_test.go
This PR contains
1. Principal string separator had to be changed as the LDAP group names also contains `,`. 
2. Now, all the RBAC tests run for both local and LDAP user.
=> Systemtests to test RBAC on LDAP user + Fixes 

Makefile, auth/ldap/ldap.go, build/Dockerfile.base, build/Dockerfile.unittests, common/types/types.go, proxy/helpers.go, scripts/systemtests.sh, scripts/unittests.sh, systemtests/basic_test.go, systemtests/ldap_management_test.go, systemtests/rbac_test.go, test/active_directory/ca.crt
This PR contains 
1. Configure `tls.Config{...}` to avoid man-in-the-middle attacks.
2. Fix broken unit-tests
=> Support TLS/SSL connection with LDAP/AD

scripts/build.sh
This saves about 500mb of space over the course of 10 builds according to `docker system df`
=> Delete the build container's volume after build is finished

scripts/systemtests_in_container.sh, scripts/unittests_in_container.sh
Basically, we want all the tests to run even if any fail.  This is basically the opposite of early aborting.
It's easy to test:  just replace the first test invocation in each script with `false` and run `make test`
=> Allow all tests to run even if a test command returns a non-0 exit status

proxy/proxy.go, scripts/systemtests.sh, systemtests/auth_test.go, systemtests/ldap_management_test.go, systemtests/local_user_test.go, systemtests/rbac_test.go
Since we sometimes use the "endpoint" variable verbatim and we sometimes concatenate stuff onto it in the test code, it's confusing to add the trailing slashes inline in the strings.  I added them as `+ "/"` so that they're easy to identify and remove later.
=> Added trailing slashes to all routes to ensure consistency with netmaster's routes

main.go, proxy/proxy.go, systemtests/init_test.go
=> Added configurable client read/write timeouts + a timeout for the netmaster request cycle + defaults for all three

main.go
(this will be useful for doing systemtests)
=> Added NO_NETMASTER_SEMVER_CHECK support for testing that netmaster is up but ignoring version incompatibilities

README.md, scripts/build.sh, scripts/build_in_container.sh
=> Updated README.md with various corrections/improvements

proxy/handlers.go, proxy/helpers.go, proxy/rbac.go, systemtests/local_user_test.go
This addresses one of the TODO items. Once the user is disabled/deleted, the associated token is no more valid.
Also, this consolidates `parseReqToken` and `isTokenValid` functions ==> `validateToken`
=> Handle cases where the user account is disabled/deleted

db/ldap_test.go
=> Fix broken CI

Makefile, auth/token.go, db/constants.go, db/local_test.go, main.go, systemtests/auth_test.go, systemtests/init_test.go
Additionally, ensure that the PRNG has been seeded
=> Token signing key is now randomly generated on demand if not already present

proxy/proxy.go, systemtests/basic_test.go
This PR makes the needed changes to avoid listing directories with static assets.
=> proxy/proxy.go: disable directory indexes

main.go
=> Use mlockall(2) to prevent pages from being swapped

scripts/build_in_container.sh
=> scripts/build_in_container.sh: switched from `strip` to -s and -w linker flags

proxy/helpers.go, systemtests/basic_test.go
=> proxy/helpers.go: return a better message when the X-Auth-Token header is missing

scripts/checks.sh
This lets things work nicely with docker-machine and SELinux-enabled systems.
=> scripts/checks.sh: rely on COPY in Dockerfile.checks rather than bindmounting

main.go
=> main.go: use runtime.Goexit() instead of sleeping in an infinite loop

build/Dockerfile.checks
=> build/Dockerfile.checks: use our Github fork of shfmt instead of the one on the author's personal domain

systemtests/basic_test.go
LDAP admin password got expired in our test setup. So, had to change it.
=> Change the expired LDAP admin password

common/test/utils.go, common/types/types.go, db/local_test.go, main.go, scripts/systemtests.sh, scripts/systemtests_in_container.sh, scripts/unittests_in_container.sh, state/authz_test.go, state/consulstatedriver.go, state/consulstatedriver_test.go, state/driverfactory.go, state/etcdstatedriver.go, state/etcdstatedriver_test.go, systemtests/init_test.go
In the past, the state store driver address's schema part indicates
the state store driver type, however, it limits https endpoints.
This commit separates the driver type and address to make it align
with updated netplugin and netmaster's CLI.
Signed-off-by: Wei Tie <nuaafe@gmail.com>
=> Separate state store driver and address
